### ISSUE TITLE
Don't use volumes to share code between nginx & fpm

### ISSUE THREAD

**Issue by morvans** [CachetHQ/Docker#106]
I think it's a bad design to use Docker volumes to share PHP source code between nginx & php-fpm containers.

Apart from the "philosophical" perspective which states that application code should leave inside the container and only data should be persisted in volumes, it's also a pain from an operational point of view.

If you want to update Cachet from vX to vY, you can't just change the tag of the image and docker-compose up -d because compose will keep on using the volume created initially, with the code of vX. You have to manually destroy php-fpm (cachet) and nginx containers and recreate it.

Unfortunately, putting application code inside container means, for that use case, building a custom nginx image with the application code, which essentially means maintaining two images. 

The other approach would be to provide a unique (simpler) image which combines the web server and the php runtime. It could also be an apache2 + mod_php image.

**Comment by djdefi** [comment]
cc #103 #46

**Comment by gamkiller77** [comment]
Also using this will not work for setup that use Kubernetes.  There is no way to share out a volume to other containers running.  We could setup a PV then copy the items over then share them but that just not clean for upgrades.

**Comment by djdefi** [comment]
Thanks @gamkiller77, I wan not aware of that behavior in Kubernetes. 

I am hoping to make some progress here soon, but have been a little short on time recently.

**Comment by morvans** [comment]
AFAICT, the only way forward is to produce two images : "cachet-fpm" & "cachet-nginx".
Or produce an image based on apache+mod_php.

**Comment by gamkiller77** [comment]
@djdefi do you have the start of the merge of cachet-nginx?  I really want to show this off to my boss as we have a massive use case for this where I work.  If you have a branch already in play I can take some time and look to help you.

**Comment by djdefi** [comment]
@gamkiller77 I dont have a branch currently.

I was thinking of just going back to how we had it before #46 and putting nginx, fpm, and the cachet code all in the same image. I am happy to review a PR if you want to take a stab at reverting those changes with the current master. I prob wont be able to work on one myself until later this week.

I am ok with doing "one purpose per container" rather than "one process per container". The image's purpose is to display Cachet, so I am 👍  with this. We have supervisord already in there for process spawning. No more volumes to share, and one less container required to be running etc.

**Comment by gamkiller77** [comment]
@djdefi I only have 3 days to work this week so i go look at this.  I was just thinking just adding the nginx at the end of the supervisor code to bring up the web end.

I have more time next week after my wedding anny.

**Comment by djdefi** [comment]
Resolved in #129
