### ISSUE TITLE
AWS elastic beanstalk support

### ISSUE THREAD

**Issue by ivanbreet** [CachetHQ/Docker#13]
Hi,

Would it be possible to add the quick-start guide for the AWS elastic beanstalk in the Readme? I've been having some trouble setting it up myself.

Regards

**Comment by djdefi** [comment]
Hi there, sorry for the delayed reply.

I do not have access to a AWS Elastic Beanstalk account currently.  If you are still trying to set this up, please open a new issue with the error you are running into. AWS's Container service is likely a better fit due to the dependencies on other containers.
