### ISSUE TITLE
Rename to cachethq/cachet || Join Docker Official Images

### ISSUE THREAD

**Issue by jgillich** [CachetHQ/Docker#146]
Search cachet on Docker hub, the official image does not show up. It should be renamed IMO.

**Comment by djdefi** [comment]
We are the top result when sorted by Downloads or stars. Not sure what criteria the "All" search sorting uses.

It would be nice to get this listed as an "official" Docker image, but I don't have the bandwidth to push that forward anytime soon.

**Comment by jgillich** [comment]
I guess it's based on multiple factors, but the image name definitely plays a big role, unlike the organization/user.

By official I meant the cachethq org, not library. Who cares if it's named `cachet` or `cachethq/cachet`.

**Comment by djdefi** [comment]
Unfortunately it doesn't seem to be possible to change the name of a Docker hub automated build once created, so a whole new build would need to be set up. 

Even if it were possible to rename, I would hesitate to rename it outright, as there are likely people using the existing image name based on the 100k+ pulls. Also, I am not sure if multiple automated builds with different names can point at the same repo on Docker hub (I don't have enough org access currently to add additional builds). 

Googling for "cachet docker" bring this repo up right under a sponsored result for Dockers 👖, and our README links to the right Docker hub build, so I think we are pretty discoverable overall. Do you find yourself needing to search for the image in the Docker hub often?

cc @GrahamCampbell @jbrooksuk for 👀

**Comment by jgillich** [comment]
Yes multiple automated builds of the same repo work fine, you can create the new image and just edit the description of the current image to tell people about the rename.

I got here by searching via Google, but didn't notice the image name in the README, instead I copied the `docker-compose.yml` (the one in the repo with `build: .`) and then went to Docker hub to look up the image. :)

**Comment by jbrooksuk** [comment]
If there is a way of marking it as official, I'd like to know how. Do we know anybody who runs DockerHub?

**Comment by jgillich** [comment]
Yes, see https://github.com/docker-library/official-images#contributing-to-the-standard-library

**Comment by jbrooksuk** [comment]
If I get time I'll try and do this, but if somebody else would like to submit it please let me know!

**Comment by wfjsw** [comment]
# Checklist for Review

-	[x] associated with or contacted upstream?
-	[x] does it fit into one of the common categories? ("service", "language stack", "base distribution")
-	[x] is it reasonably popular, or does it solve a particular use case well?
-	[ ] does a [documentation](https://github.com/docker-library/docs/blob/master/README.md) PR exist? (should be reviewed and merged at roughly the same time so that we don't have an empty image page on the Hub for very long)
     - Should be moved from [docs.cachethq.io](https://docs.cachethq.io/docs/get-started-with-docker) to `README.md`. [MINOR]
-	[ ] dockerization review for best practices and cache gotchas/improvements (ala [the official review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines))?
    - Cache: There is no version lock in package manager which installs PHP. [MAJOR]
-	[ ] 2+ dockerization review?
    - Might have, not sure. [MINOR]
-	[ ] existing official images have been considered as a base? (ie, if `foobar` needs Node.js, has `FROM node:...` instead of grabbing `node` via other means been considered?)
    - Not sure since we are installing php from package
-	[ ] ~~if `FROM scratch`, tarballs only exist in a single commit within the associated history?~~
-	[ ] passes current tests? any simple new tests that might be appropriate to add? (https://github.com/docker-library/official-images/tree/master/test)
    - TODO

**Comment by jbrooksuk** [comment]
👍🏻

**Comment by wfjsw** [comment]
The usage of docker-compose is not a common behavior for official images, I'm afraid.

**Comment by djdefi** [comment]
Does it make sense to switch to one of the official alpine based `php` base images?

**Comment by wfjsw** [comment]
No idea. Gotta take a look soon.

**Comment by djdefi** [comment]
Wondering if anyone still wants to pursue this? I can't commit to taking it on personally.

**Comment by wfjsw** [comment]
I'm not sure. I think this plus is not so useful as we are recommending docker-compose and `build`

**Comment by J0WI** [comment]
I would be interested to use upstream PHP images and getting rid of supervisord.
Would you accept such changes?

**Comment by wfjsw** [comment]
Obsoleted. Drop it.

@J0WI Feel free to submit pr and we will happy to review it.
