### ISSUE TITLE
Best way to move a docker image from one server to another.

### ISSUE THREAD

**Issue by moodhairboy** [CachetHQ/Docker#147]
What is the best practice to move a cachetHQ docker image from one server to another and preserving the data? I am running cachetHQ in a docker container on my macbook - but I have a production centos server that I want to move the docker container to. I do not want to lose all of my data in the process. Is there another tool other than Flocker or is there a how to guide available for a relative newb?

**Comment by moodhairboy** [comment]
ok - maybe a different take on the question.  How do I avoid not losing the data in the Postgres SQL DB in the Docker Container?  What is the best practive for storing or locating the DB outside of the container?

**Comment by djdefi** [comment]
You can do a [SQL Dump export](https://www.postgresql.org/docs/9.1/static/backup-dump.html) the SQL data and import to a different instance.

Another option would be to [mount the `/var/lib/postgresql/data` directory directly to your host](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume). Since we are using the official [Postgres Image](https://hub.docker.com/_/postgres/) this should be pretty straigtforward. You can then backup that directory to a different host, and mount it to that system's instance of postgres etc. The https://docs.docker.com/engine/tutorials/dockervolumes/ is a good read to learn more about managing data in Docker.

Hopefully this helps.

**Comment by moodhairboy** [comment]
Thanks for the info I appreciate it.
