### ISSUE TITLE
Connect Redis with Cachet

### ISSUE THREAD

**Issue by Oaktr33** [CachetHQ/Docker#261]
Hey guys, hoping you can guide me in the right direction here...
Was asked to implement Cachet at my company but I'm not a developer and am having a hard time setting up the cache-side of it.

Didn't have any issues with setting up Cachet with Docker in my localhost but would like as well to see it running with Redis cache.

From what I've been reading, the best way to make Redis work along with Cachet in Docker is by running a different container and link them both together...

My question is: what exactly do I need to change in .env and .yml files so that I make it happen? Or...is there an easier solution to this?

Really just trying to get some guidance here! Any input is greatly appreciated guys!

BTW, Cachet is awesome, was really easy to make a business case to show my superiors 😄

**Comment by djdefi** [comment]
It should just be a matter of linking a redis container, and setting the relevant redis ENV variables, however I believe this won't work until we have a 2.4 release, so that Cachet includes the predis dependency.

I started a branch here which is pretty close, but does require an image to be built from the upstream 2.4 branch : https://github.com/CachetHQ/Docker/tree/redis-test

Once 2.4 is generally available, I think we can look at supporting an optional external redis image, if there is interest and benefits to doing so.

We currently default to the PHP apc cache driver, which seems to work pretty well in most cases, although I haven't really done extensive testing in that area. Performance with the defaults always has seemed good enough.

**Comment by Oaktr33** [comment]
@djdefi Thanks for the insight! I might have to rethink it then and go with APC instead of Redis. Thanks man!

**Comment by djdefi** [comment]
It should just be a matter of choosing APC during the setup / setting in in the environment. #336 makes it the default as well.
